-- WSO2 API Manager Standard Schema (Sample)
-- Version: 4.6.0

CREATE TABLE IF NOT EXISTS AM_API (
                                      API_ID INTEGER NOT NULL AUTO_INCREMENT,
                                      API_UUID VARCHAR(256) NOT NULL,
    API_PROVIDER VARCHAR(256) NOT NULL,
    API_NAME VARCHAR(256) NOT NULL,
    API_VERSION VARCHAR(30) NOT NULL,
    CONTEXT VARCHAR(256) NOT NULL,
    CONTEXT_TEMPLATE VARCHAR(256),
    API_TIER VARCHAR(256),
    API_TYPE VARCHAR(50) DEFAULT 'API',
    ORGANIZATION VARCHAR(100) NOT NULL,
    GATEWAY_VENDOR VARCHAR(100) DEFAULT 'wso2',
    CREATED_BY VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_BY VARCHAR(100),
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    STATUS VARCHAR(30) DEFAULT 'CREATED',
    PRIMARY KEY (API_ID),
    UNIQUE (API_UUID),
    UNIQUE (API_PROVIDER, API_NAME, API_VERSION, ORGANIZATION)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS AM_APPLICATION (
                                              APPLICATION_ID INTEGER NOT NULL AUTO_INCREMENT,
                                              NAME VARCHAR(100) NOT NULL,
    SUBSCRIBER_ID INTEGER NOT NULL,
    APPLICATION_TIER VARCHAR(50) DEFAULT 'Unlimited',
    CALLBACK_URL VARCHAR(512),
    DESCRIPTION VARCHAR(512),
    APPLICATION_STATUS VARCHAR(50) DEFAULT 'APPROVED',
    GROUP_ID VARCHAR(100),
    CREATED_BY VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UUID VARCHAR(256) NOT NULL,
    TOKEN_TYPE VARCHAR(100) DEFAULT 'JWT',
    ORGANIZATION VARCHAR(100) NOT NULL,
    PRIMARY KEY (APPLICATION_ID),
    UNIQUE (UUID),
    UNIQUE (NAME, SUBSCRIBER_ID, ORGANIZATION)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS AM_SUBSCRIBER (
                                             SUBSCRIBER_ID INTEGER NOT NULL AUTO_INCREMENT,
                                             USER_ID VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER DEFAULT 0,
    EMAIL_ADDRESS VARCHAR(256),
    DATE_SUBSCRIBED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (SUBSCRIBER_ID),
    UNIQUE (USER_ID, TENANT_ID)
    ) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS AM_SUBSCRIPTION (
                                               SUBSCRIPTION_ID INTEGER NOT NULL AUTO_INCREMENT,
                                               TIER_ID VARCHAR(50) NOT NULL,
    TIER_ID_PENDING VARCHAR(50),
    API_ID INTEGER NOT NULL,
    APPLICATION_ID INTEGER NOT NULL,
    SUB_STATUS VARCHAR(50) DEFAULT 'UNBLOCKED',
    SUBS_CREATE_STATE VARCHAR(50) DEFAULT 'SUBSCRIBE',
    CREATED_BY VARCHAR(100),
    CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UUID VARCHAR(256) NOT NULL,
    PRIMARY KEY (SUBSCRIPTION_ID),
    UNIQUE (UUID),
    FOREIGN KEY (API_ID) REFERENCES AM_API(API_ID) ON DELETE CASCADE,
    FOREIGN KEY (APPLICATION_ID) REFERENCES AM_APPLICATION(APPLICATION_ID) ON DELETE CASCADE
    ) ENGINE=InnoDB;

-- Indexes
CREATE INDEX IDX_AM_API_PROVIDER ON AM_API(API_PROVIDER);
CREATE INDEX IDX_AM_API_CONTEXT ON AM_API(CONTEXT);
CREATE INDEX IDX_AM_API_ORGANIZATION ON AM_API(ORGANIZATION);
CREATE INDEX IDX_AM_APPLICATION_SUBSCRIBER ON AM_APPLICATION(SUBSCRIBER_ID);
CREATE INDEX IDX_AM_SUBSCRIPTION_API ON AM_SUBSCRIPTION(API_ID);
CREATE INDEX IDX_AM_SUBSCRIPTION_APP ON AM_SUBSCRIPTION(APPLICATION_ID);